// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_interlink

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func InterlinkProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Required: true,
			},
			"api_url": schema.StringAttribute{
				Optional: true,
			},
		},
	}
}

type InterlinkModel struct {
	ApiKey types.String `tfsdk:"api_key"`
	ApiUrl types.String `tfsdk:"api_url"`
}
